### ISSUE TITLE
Function renaming proposal

### ISSUE THREAD

**Issue by ADRFranklin** [Southclaws/samp-logger#8]
I wish to propose a function name change, due to the current naming scheme it causes a lot of problems with other libraries, libraries that use common names like `err`, `dbg`, and `log`. 

So I want to propose that we instead change the functions to a proper naming scheme, so instead of a function like `err` we would now use it like `Logger_Err` and for the types that are used, we instead use `Logger_I` instead of `_i`. This adds a lot more clarity to what package this function belongs to, and escapes the possibility of causing warnings for the end user.

Here I will provide an example from the readme file that shows the current and the new proposed changes.

current:
```
log("something happened!");

logger_debug("weapons", true); // activate the "weapons" debug handler
dbg("weapons", "player changed weapon",
    _i("weaponid", 31));
```

new changes:
```
Logger_Log("something happened!");

Logger_Debug("weapons", true); // activate the "weapons" debug handler
Logger_Dbg("weapons", "player changed weapon",
    Logger_I("weaponid", 31));
```

I would also like the propose the ability to define a compatibility definition, that would toggle between the old functions and the new ones. This way people who are currently happy using the library as is, don't need to be forced to make changes to their gamemode, should they decide to upgrade past this proposal. 

The proposed compatibility definition would be called `SAMP_LOGGER_COMPAT` which would mean that current library users would still need to define `SAMP_LOGGER_COMPAT` to continue using the old version of the functions.

**Comment by spacemud** [comment]
:shipit:

**Comment by spacemud** [comment]
I'd suggest naming `Logger_Debug` to `Logger_ToggleDebug` to make its purpose a bit clearer and avoid confusion with the actual logging functions.

**Comment by ADRFranklin** [comment]
Yeah, that makes more sense.
